### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-F10-4

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F10-4/main#338]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [ ] Milestone explicitly closed(:exclamation:)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @e0323290 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-4/main/issues/257 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/256 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/247 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/242 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @jessteoxizhi for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-4/main/issues/190 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/174 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @jasonleeweihern for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-4/main/issues/313 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/310 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/278 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/271 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @yueyuu for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-4/main/issues/300 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/299 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/298 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/279 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/183 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/118 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/1 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @mononokehime14 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-4/main/issues/264 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/263 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/262 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/260 https://github.com/AY1920S1-CS2113T-F10-4/main/issues/259 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @langyanbin0314

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-15 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
